### ISSUE TITLE
Provide way to ensure all variables have values provided

### ISSUE THREAD

**Issue by lewisf** [bhgames/json-logic-ruby#15]
The JS library exposes a function called `uses_data` which is useful to check if all variables have data in provided data.

https://github.com/jwadhams/json-logic-js/issues/39#issuecomment-339031252

It'd be awesome to have this in this ruby implementation too so that we can do validation that all the variable values are available before trying to evaluate (which could lead to weird errors)

**Comment by bhgames** [comment]
Release v0.4.5 addresses this. Thanks for the PR!
