### ISSUE TITLE
There is no 0.2 version

### ISSUE THREAD

**Issue by Azael05x** [bhgames/json-logic-ruby#4]
https://rubygems.org/gems/json_logic stores only 0.1 there is no version supporting added add_method from here: https://github.com/kennethgeerts/json-logic-ruby/commit/48568b6a33a13a77706f5480f51bfcafb95cae33

**Comment by bhgames** [comment]
@Azael05x check out my PR. It is compliant with the spec and I believe has what you need.

**Comment by bhgames** [comment]
@Azael05x I now own this repository, and I'll be updating the gem soon to be working.

**Comment by bhgames** [comment]
Okay, the new version is 0.3. Please update.
